name: Auto publish and create release

on:
  push:
    branches: [ "master", "next" ]
  pull_request:
    branches: [ "master" ]

jobs:
  autorelease:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: git fetch --unshallow --tags
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Auto release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run build --if-present
          npx auto shipit